name: console_cam
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  image: ^3.2.0
  escapi: {path: 'packages/escapi'}
  args: ^2.3.1
  path: ^1.8.2
  logging: ^1.0.2
  console: ^4.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
